services:
  db:
    image: mysql:8.0
    container_name: lms-db
    restart: always
    environment:
      MYSQL_DATABASE: lms_backend_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lmspass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lms-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lms-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lms_backend_db
      SPRING_DATASOURCE_USERNAME: lmsuser
      SPRING_DATASOURCE_PASSWORD: lmspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8085"
    networks:
      - lms-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: lms-frontend
    restart: always
    ports:
      - "5173:8082"
    depends_on:
      - backend
    networks:
      - lms-net

volumes:
  db_data:

networks:
  lms-net:
    driver: bridge

